[options]
admin_passwd = admin1
;db_name = opsway-test
db_host = opsway-db
db_port = 5432
db_user = odoo
db_password = myodoo
db_list = True
addons_path = /mnt/extra-addons,/mnt/addons-third-party,/mnt/enterprise,/mnt/submodules/odoo_secure_cookies_support
data_dir = /var/lib/odoo
max_cron_threads = 1
limit_time_cpu = 6000
limit_time_real = 12000
workers = 4
