[options]
admin_passwd = admin
db_host = postgres
db_port = 5432
db_user = odoo
db_password = myodoo
db_name = db-test
db_list = True
addons_path = /mnt/extra-addons,/mnt/addons-third-party,/mnt/submodules,/mnt/submodules/odoo_secure_cookies_support,/mnt/enterprise
data_dir = /var/lib/odoo
max_cron_threads = 0
workers = 0
without_demo = all
stop_after_init = True
test_enable = True
test_tags = PROJECT_NAME_init,-slow
