{
    'name': "Internal Opsway Init",
    'version': "18.0.1.0.0",
    'summary': "Internal Opsway modules initialization",
    'description': "Install all Internal Opsway modules.",
    'author': "Lumirang",
    'website': "https://lumirang.com",
    'license': "Other proprietary",
    'depends': [
        'base',
        'account_analytic_percentage',
        'account_partner_default_recipient_bank',
        'account_validation_by_currency',
        'opsway_account_payment',
        'opsway_employee_bill',
        'pdf_intellectual_property',
        'currency_name_res_partner_bank',
        'sh_email_enhancement',
        'sh_email_enhancement_extension',
        'web_one2many_duplicate_cr',
        'account_reports_exclude_analytics',
        # 'odoo_secure_cookies_support',  # TODO: make sure that this module will be available in CI and AI flow,
        #  then uncomment
    ],
    'data': [],
    'installable': True,
    'application': True,
    'auto_install': False,
    'sequence': 1,
}
