name: Check Documentation Structure

on:
  pull_request:
    branches:
      - 'stage'
      - 'Live'
    types: [ 'closed','opened','synchronize' ]
jobs:
  check-doc-structure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Clone reference repo
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          if [[ $GH_PAT != '' ]]; then
            git clone --depth 1 --branch main https://$GH_PAT@github.com/opsway/odoo_sop.git _reference_repo
          else
            git clone --depth 1 --branch main https://github.com/opsway/odoo_sop.git _reference_repo
          fi

      - name: Compare doc structure
        run: |
          python _reference_repo/scripts/compare_doc_structure.py
