name: Code review response
# Copy this workflow to the repository where you want AI agent to respond on PR reviews
on:
  pull_request_review:
    types: [edited, submitted]

run-name: Code review response for ${{ inputs.jira_id }}

jobs:
  code-review-response:
    if: github.event.review.state == 'changes_requested' && github.event.pull_request.user.login == vars.AI_PR_AUTHOR
    uses: opsway/ai_tooling/.github/workflows/coder-agent.yml@${{ if(contains(github.event.pull_request.labels.*.name, 'test_ai'), 'dev', 'master') }}
    with:
      jira_id: ''
      spent: '0'
      budget: '2'
      qa_note: 'See comments added to the pull request #${{ github.event.pull_request.number }}'
      stage_branch: ${{ vars.STAGE_BRANCH }}
      starting_branch: ${{ github.event.pull_request.head.ref }}
      feature_branch: ${{ github.event.pull_request.head.ref }}
      jira_username: ${{ vars.JIRA_USERNAME }}
      jira_url: ${{ vars.JIRA_URL }}
      init_odoo_addons: ${{ vars.INITIAL_ODOO_ADDONS }}
      DOCKER_COMPOSE_DIR: ${{ vars.DOCKER_COMPOSE_DIR }}
      ENTERPRISE_DIR: ${{ vars.ENTERPRISE_DIR }}
      ODOO_SERVICE_NAME: ${{ vars.ODOO_SERVICE_NAME }}
      DATABASE_SERVICE_NAME: ${{ vars.DATABASE_SERVICE_NAME }}
      odoo_branch: ${{ vars.ODOO_BRANCH }}
    secrets:
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      ODOO_ENTERPRISE_SECRET: ${{ secrets.ODOO_ENTERPRISE_SECRET }}
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      GH_PAT: ${{ secrets.GH_PAT }}
      QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
