name: Tests
on:
  pull_request:
    branches:
      - 'stage'
      - 'Live'
    types: [ 'closed','opened','synchronize' ]
jobs:
  odoo-tests:
    name: Odoo tests
    runs-on: ubuntu-latest
    container:
      image: quay.io/opsway/odoo:opsway
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      PGHOST: postgres
      PGDATABASE: odoo-test
      PGUSER: odoo
      PGPASSWORD: myodoo
    services:
      postgres:
        image: postgres:14.7
        env:
          POSTGRES_USER: odoo
          POSTGRES_PASSWORD: myodoo
          POSTGRES_DB: odoo-test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Prepare odoo addons
        env:
          ODOO_ENTERPRISE_SECRET: ${{secrets.ODOO_ENTERPRISE_SECRET}}
          ENTERPRISE_REVISION: ${{vars.ENTERPRISE_REVISION}}
          ODOO_BRANCH: ${{vars.ODOO_BRANCH}}
        shell: bash
        run: |
          git config --global --add safe.directory /__w/internal/internal
          git config --global --add safe.directory /mnt/enterprise
          mkdir -p /mnt/enterprise
          chown -R odoo /mnt/enterprise
          mkdir -p $HOME/.ssh
          echo "$ODOO_ENTERPRISE_SECRET" > $HOME/.ssh/id_rsa
          chmod 600 $HOME/.ssh/id_rsa
          export GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no -i $HOME/.ssh/id_rsa"
          git clone --branch $ODOO_BRANCH --depth=1 git@github.com:odoo/enterprise.git /mnt/enterprise
          cd /mnt/enterprise
          git fetch origin $ENTERPRISE_REVISION
          git checkout $ENTERPRISE_REVISION
      - name: Prepare odoo folders
        run: |
          mv addons/* /mnt/extra-addons 
          if [ "$(ls submodules)" ]; then mv submodules/* /mnt/submodules; fi
          if [ "$(ls addons_third_party)" ]; then mv addons_third_party/* /mnt/addons-third-party; fi 
          mv env/common/test-odoo.conf $HOME/odoo.conf
      - name: Run unit tests
        env:
          INIT_ADDONS: ${{vars.INITIAL_ODOO_ADDONS}}
        run: python3 -u /usr/bin/odoo --conf $HOME/odoo.conf -i $INIT_ADDONS
